spring:
  mail:
    host: smtp.gmail.com          # 구글 SMTP 서버 주소
    port: 587                     # 구글 SMTP 포트 번호
    username: ${GOOGLE_MAIL_ADDRESS}  # 사용자 이메일
    password: ${GOOGLE_MAIL_PASSWORD} # 사용자 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 여부
          timeout: 5000           # 이메일 전송 타임아웃 시간
          starttls:
            enable: true          # TLS를 통해 안전한 통신 사용 여부

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  config:
    import: optional:file:.env[.properties]

  messages:
    basename: messages,errors

  profiles:
    active: local

  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g5e032b82f1589c_jwshop_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10   # 12GB 메모리를 Redis/MySQL과 나눠 써야 하니 넉넉하게 잡지 않는 게 안전합니다


  jpa:
    hibernate:
      ddl-auto: validate    # 최초시에만 create, 나머지 validate
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
#        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  servlet:
    session:
      timeout: 6000   #세션 타임아웃 설정(기본:초)
      tracking-modes: cookie  #첫 로그인할 경우 jsessionid 404오류 해결


solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  sender: ${SOLAPI_SENDER}

file:
  path: ${FILE_STORE_PATH}
  exteral-path: ${FILE_EXTERNAL_STORE_PATH}

redis:
  ttl:
    timeout: 200   #단위:초

jwt:
  secret: ${JWT_SECRET}